### ISSUE TITLE
Grammar check fails - Resource punkt not found.

### ISSUE THREAD

**Issue by kate-holdener** [oss-slu/SpeechTranscription#55]
I was running this software with Python 3.10. Uploaded a short audio that I recorded and successfully transcribed it. When I clicked on the "Grammar check" button, I saw the following error in the terminal:

```
**********************************************************************

Exception in Tkinter callback
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/Users/holdenerea/repos/SpeechTranscription/GUI.py", line 208, in inflectionalMorphemes
    converting = addConventions.addInflectionalMorphemes(converting)
  File "/Users/holdenerea/repos/SpeechTranscription/functions/addConventions.py", line 59, in addInflectionalMorphemes
    sentences = sent_tokenize(x)
  File "/Users/holdenerea/repos/SpeechTranscription/venv/lib/python3.10/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
  File "/Users/holdenerea/repos/SpeechTranscription/venv/lib/python3.10/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
  File "/Users/holdenerea/repos/SpeechTranscription/venv/lib/python3.10/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
  File "/Users/holdenerea/repos/SpeechTranscription/venv/lib/python3.10/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/Users/holdenerea/nltk_data'
    - '/Users/holdenerea/repos/SpeechTranscription/venv/nltk_data'
    - '/Users/holdenerea/repos/SpeechTranscription/venv/share/nltk_data'
    - '/Users/holdenerea/repos/SpeechTranscription/venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

**Comment by kate-holdener** [comment]
When I clicked "add morphemes", got an error message saying that I need to add:
```
nltk.download('wordnet')
```

**Comment by jakewahle** [comment]
Sorry, we forgot to detail our process for downloading nltk. After doing "pip install nltk", you should open the python interpreter, type "import nltk" then nltk.download(). This will bring up the screen below.

![Screenshot (37)](https://user-images.githubusercontent.com/37639498/232148673-5b7e0c6d-74ba-4fe9-b90f-7a0132cee86f.png)

Here, click on the identifier "all", then download.
